name: Jest Tests

on:
  pull_request:
    branches: [main]

jobs:
  test:
    name: jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        run: |
          npm install 
          npm test